{% set version = "1.0-98102e9" %}
{% set sha256 = "f73d80be084dc73128d4795e9d03abcd35be2ddc7ef81684fcadec154a28b7af" %}

package:
  name: metamaps
  version: {{ version }}

source:
  url: https://github.com/DiltheyLab/MetaMaps/archive/98102e9e684efa6a9903d8abe93600132c101ad0.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - autoconf
  host:
    - zlib
    - boost-cpp
    - perl
    - r-base
  run:
    - zlib
    - boost-cpp
    - perl
    - r-base
test:
  commands:
    - metamaps -h

about:
  home: https://github.com/DiltheyLab/MetaMaps
  license: Public Domain
  license_family: Public Domain
  license_file: LICENSE.txt
  summary: MetaMaps is a tool for long-read metagenomic analysis
