package:
  name: emboss
  version: "6.6.0"

build:
  number: 0

source:
  url: ftp://emboss.open-bio.org/pub/EMBOSS/EMBOSS-6.6.0.tar.gz
  md5: 6a2cb3f93d5e9415c74ab0f6b1ede5f0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - zlib
    - libgd
    - libpng
  run:
    - zlib
    - libgd
    - libpng

about:
  home: http://emboss.open-bio.org/
  license: GPL
  summary: The European Molecular Biology Open Software Suite

test:
  commands:
    # test a few tools
    -  needle --help
    -  transeq --help
    -  sixpack --help
    -  seqret --help
