package:
  name: python-chado
  version: "2.2.0"

source:
  url: https://files.pythonhosted.org/packages/2d/0e/6b3103d8e3321721e4643d82f96b81a41b65e160da34f608ac065af82cc2/chado-2.2.0.tar.gz
  sha256: 40325540fb196b786dded0118aaec33d15fbcc5e078355d621896edcad825e7c

build:
  noarch: python
  number: 0

requirements:
  host:
    - python
    - setuptools
    - sqlalchemy
    - psycopg2
    - biopython
    - bcbiogff >=0.6.4
    - wrapt
    - click
    - pyyaml

  run:
    - python
    - sqlalchemy
    - psycopg2
    - biopython
    - bcbiogff >=0.6.4
    - wrapt
    - click
    - pyyaml
    - future

test:
  imports:
    - chado
    - chado.analysis
    - chado.export
    - chado.organism
    - chado.util

  commands:
    - chakin --help > /dev/null
    - chakin analysis --help > /dev/null

about:
  home: https://github.com/galaxy-genome-annotation/python-chado
  license: MIT License
  summary: 'Chado library'
  license_family: MIT

extra:
  container:
    # unicode problem with click
    extended-base: true
