package:
  name: python-tripal
  version: "3.1"

source:
  url: https://files.pythonhosted.org/packages/c9/04/f4e09b819f08deb145157a15590abaeb3b3a9fd0873442a1c2b7d0dcf208/tripal-3.1.tar.gz
  sha256: 20093c042cbe5e9dcca1f59d130636d0551161bc2d0fc16eb30f7b933fe4deb6

build:
  noarch: python
  number: 1

requirements:
  host:
    - python
    - setuptools
    - requests >=2.4.3
    - wrapt
    - click
    - pyyaml

  run:
    - python
    - requests >=2.4.3
    - wrapt
    - click
    - pyyaml
    - future

test:
  imports:
    - tripal
    - tripal.analysis
    - tripal.db
    - tripal.feature
    - tripal.job
    - tripal.organism
    - tripal.phylogeny

  commands:
    - tripaille --help > /dev/null
    - tripaille analysis --help > /dev/null

about:
  home: https://github.com/galaxy-genome-annotation/python-tripal
  license: MIT License
  summary: 'Tripal API library'
  license_family: MIT

extra:
  container:
    # unicode problem with click
    extended-base: true
  identifiers:
    - biotools:tripal
