package:
  name: fastsimbac
  version: '1.0.1_bd3ad13d8f79'

source:
  url: "https://bitbucket.org/nicofmay/fastsimbac/get/bd3ad13d8f79.zip"
  md5: "7c183b317bc45606f6b37e27f6ee8357"

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - boost
  run:
    - boost

test:
  commands:
    - test -e ${PREFIX}/include/gatb/bank/api/Sequence.hpp

about:
  home: https://bitbucket.org/nicofmay/fastsimbac/
  license: GPL
  summary: Models bacterial recombination
