{% set version = "0.23" %}

package:
  name: circos-tools
  version: {{ version }}

source:
  url: http://circos.ca/distribution/circos-tools-{{ version }}.tgz
  sha256: 0c5404ff88f621ce945fd6bf770cb56872f79c4a3a36715cb7dd3ed2280e8bfe

build:
  number: 0

requirements:
  run:
    - perl
    - perl-bioperl
    - perl-carp
    - perl-config-general
    - perl-data-dumper
    - perl-file-path
    - perl-findbin
    - perl-getopt-long
    - perl-graphics-colorobject
    - perl-list-moreutils
    - perl-math-random
    - perl-math-round
    - perl-math-vecstat
    - perl-memoize
    - perl-pod-usage
    - perl-regexp-common
    - perl-set-intspan
    - perl-statistics-descriptive
    - perl-time-hires

test:
  commands:
    - binlinks -help
    - bundlelinks -help
    - calcdatarange -help
    - parse-category -help
    - clustal2link -help
    - colorinterpolate -help
    - convertlinks -help
    - filterlinks -help
    - orderchr -help
    - randomdata -help
    - randomlinks -help
    - resample -help
    - make-conf -help
    - make-table -help
    - parse-table -help


about:
  home: http://circos.ca
  summary: circos-tools provides several utility add-on scripts, such as for bundling links
  license: GNU General Public License v2 (GPLv2)
  license_family: GPL2
