{% set version = "1.16.1" %}
package:
  name: jbrowse
  version: {{ version }}
build:
  number: 0
source:
  sha256: 41a3715e4e0ee9c9f0c8d0f1d9d07add21e4f1f16bc58309109733ed22085ec1
  url: https://github.com/GMOD/jbrowse/releases/download/{{ version }}-release/JBrowse-{{ version }}.zip

requirements:
  build:
  run:
    - perl
    - perl-json
    - perl-clone
    - perl-io-string
    - perl-bioperl
    - perl-test-differences
    - perl-test-deep
    - perl-test-most
    - perl-test-exception
    - perl-test-nowarnings
    - perl-test-simple
    - perl-test-warn
    - perl-exporter-tiny
    - perl-list-moreutils
    - perl-class-data-inheritable
    - perl-devel-stacktrace
    - perl-exception-class
    - perl-sub-uplevel
    - perl-algorithm-diff
    - perl-capture-tiny
    - perl-text-diff
    - perl-data-stag
    - perl-uri
    - perl-scalar-list-utils
    - perl-perlio-gzip
    - perl-bio-gff3
    - perl-devel-size
    - perl-digest-crc32
    - perl-file-next
    - perl-hash-merge
    - perl-heap-simple
    - perl-text-tabs-wrap
    - perl-db-file
    - perl-bio-featureio
    - perl-io-uncompress-gunzip
    - perl-file-copy-recursive
    - perl-local-lib


test:
  commands:
    - command -v add-json.pl
about:
  home: https://jbrowse.org/
  license: LGPL
  summary: The JBrowse Genome Browser

extra:
  identifiers:
    - biotools:jbrowse
    - doi:10.1101/gr.094607.109
