package:
  name: perl-bio-db-sam
  version: '1.41'

source:
  url: https://cpan.metacpan.org/authors/id/L/LD/LDS/Bio-SamTools-1.41.tar.gz
  sha256: b5d7ca16c96cc9fbee5daceb3268f36011740fe4de92074c17a729bac57c3077

build:
  number: 4
  skip: True # [osx]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - perl
    - perl-app-cpanminus
    - perl-module-build
    - perl-bioperl
    - perl-bio-samtools
    - wget
    - zlib
    - samtools 0.1.19.*
  run:
    - perl
    - perl-bioperl
    - perl-bio-samtools
    - zlib
    - samtools 0.1.19.*

test:
  imports:
    - Bio::DB::Sam

about:
  home: https://metacpan.org/pod/Bio::DB::Sam
  license: Perl
  summary:  Read SAM/BAM database files
